apiVersion: v1
kind: Pod
metadata:
  name: geo-map-service
  labels:
    app: geo-map-service

spec:
  containers:
  - name: geo-coord
    resources:
      requests:
        memory: "2Gi"
      limits:
        memory: "4Gi"
    image: sokoloid/geo_map:v1
    ports:
      - containerPort: 8000
    command: ['python', '/src/model/app_fast_api.py']
