apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: my-repl-set
    labels:
      app: geo-map-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: geo-map-service
  template:
    metadata:
      name: my-repl-set
      labels:
        app: geo-map-service


    spec:
      containers:
      - name: geo-coord
        resources:
          requests:
            memory: "2Gi"
          limits:
            memory: "4Gi"
        image: sokoloid/geo_map:v2
        ports:
          - containerPort: 8000
        command: ['python', '/src/model/app_fast_api.py']
