defaults:
  - map: kazan_cfg.yaml

  # путь к корневому каталогу
path_to_root: ../../
  # путь от корневого каталога до изображения карты


walks_file: data\interim\walks4.txt
model_save: best_model_crop32.pkl
train_val_ratio: 0.8
batch_size: 512
crop_size: 16
walk_step: 1
class_cnt: 18
deviation: 3
epoch: 20
lr: 0.001

